default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: timetracker_development
  host: '' 
  port: 5432

test:
  <<: *default
  database: timetracker_test
  host: ''
  port: 5432

production:
  <<: *default
  database: timetracker_production
  username: timetracker
  password: <%= ENV['TIMETRACKER_DATABASE_PASSWORD'] %>
